-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/shelf_cascade/shelf_cascade.vhd
-- Created: 2024-11-15 15:51:59
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.08333e-05
-- Target subsystem base rate: 2.08333e-05
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.08333e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- DataOut                       ce_out        2.08333e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: shelf_cascade
-- Source Path: shelf_cascade
-- Hierarchy Level: 0
-- Model version: 1.20
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY shelf_cascade IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        DataIn                            :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        ce_out                            :   OUT   std_logic;
        DataOut                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
        );
END shelf_cascade;


ARCHITECTURE rtl OF shelf_cascade IS

  -- Component Declarations
  COMPONENT Subsystem16
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem16
    USE ENTITY work.Subsystem16(rtl);

  -- Signals
  SIGNAL Subsystem16_out1                 : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Subsystem16 : Subsystem16
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              DataIn => DataIn,  -- sfix24_En23
              DataOut => Subsystem16_out1  -- sfix32_En23
              );

  ce_out <= clk_enable;

  DataOut <= Subsystem16_out1;

END rtl;

