-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/shelf_cascade/Subsystem16.vhd
-- Created: 2024-11-15 15:51:59
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem16
-- Source Path: shelf_cascade/Subsystem16
-- Hierarchy Level: 1
-- Model version: 1.20
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem16 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        DataIn                            :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        DataOut                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
        );
END Subsystem16;


ARCHITECTURE rtl OF Subsystem16 IS

  -- Component Declarations
  COMPONENT Subsystem1
    PORT( K                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          V                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha2K_not_ascii_V_2V_1_2      :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   OUT   std_logic_vector(26 DOWNTO 0)  -- sfix27_En23
          );
  END COMPONENT;

  COMPONENT Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
          alpha1_a0                       :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a1                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a2                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha1_a0                       :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a1                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a2                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha1_a0                       :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a1                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a2                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem5
    PORT( K                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          V                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha2K_not_ascii_V_2V_1_2      :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29_En23
          );
  END COMPONENT;

  COMPONENT Subsystem4
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha1_a0                       :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a1                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a2                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem6
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha1_a0                       :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a1                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a2                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem7
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha1_a0                       :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a1                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a2                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem9
    PORT( K                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          V                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha2K_not_ascii_V_2V_1_2      :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   OUT   std_logic_vector(26 DOWNTO 0)  -- sfix27_En23
          );
  END COMPONENT;

  COMPONENT Subsystem8
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha1_a0                       :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a1                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a2                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem10
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha1_a0                       :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a1                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a2                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem11
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha1_a0                       :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a1                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          a2                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem13
    PORT( K                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          V                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          alpha2K_not_ascii_V_2V_1_2      :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29_En23
          );
  END COMPONENT;

  COMPONENT Subsystem12
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha1_a0                       :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a1                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a2                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem14
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha1_a0                       :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a1                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a2                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  COMPONENT Subsystem15
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          DataIn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha1_a0                       :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a1                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          a2                              :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          alpha2K_not_ascii_V_2V_1_2      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          K_not_ascii_V_2V_1_1            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          alpha2K_V_1                     :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En23
          Cm                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En23
          Enable                          :   IN    std_logic;
          DataOut                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En23
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem1
    USE ENTITY work.Subsystem1(rtl);

  FOR ALL : Subsystem
    USE ENTITY work.Subsystem(rtl);

  FOR ALL : Subsystem2
    USE ENTITY work.Subsystem2(rtl);

  FOR ALL : Subsystem3
    USE ENTITY work.Subsystem3(rtl);

  FOR ALL : Subsystem5
    USE ENTITY work.Subsystem5(rtl);

  FOR ALL : Subsystem4
    USE ENTITY work.Subsystem4(rtl);

  FOR ALL : Subsystem6
    USE ENTITY work.Subsystem6(rtl);

  FOR ALL : Subsystem7
    USE ENTITY work.Subsystem7(rtl);

  FOR ALL : Subsystem9
    USE ENTITY work.Subsystem9(rtl);

  FOR ALL : Subsystem8
    USE ENTITY work.Subsystem8(rtl);

  FOR ALL : Subsystem10
    USE ENTITY work.Subsystem10(rtl);

  FOR ALL : Subsystem11
    USE ENTITY work.Subsystem11(rtl);

  FOR ALL : Subsystem13
    USE ENTITY work.Subsystem13(rtl);

  FOR ALL : Subsystem12
    USE ENTITY work.Subsystem12(rtl);

  FOR ALL : Subsystem14
    USE ENTITY work.Subsystem14(rtl);

  FOR ALL : Subsystem15
    USE ENTITY work.Subsystem15(rtl);

  -- Signals
  SIGNAL Constant12_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant1_out1                   : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant_out1                    : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL K_1                              : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL V_1                              : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL alpha2K_not_ascii_V_2V_1_2       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL K_not_ascii_V_2V_1_1             : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL alpha2K_V_1                      : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL Constant4_out1                   : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant5_out1                   : std_logic;
  SIGNAL Subsystem_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant6_out1                   : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant3_out1                   : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant2_out1                   : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant7_out1                   : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant8_out1                   : std_logic;
  SIGNAL Subsystem2_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant11_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant10_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant9_out1                   : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant13_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant14_out1                  : std_logic;
  SIGNAL Subsystem3_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant19_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant16_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant15_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL K_2                              : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL V_2                              : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL alpha2K_not_ascii_V_2V_1_2_1     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL K_not_ascii_V_2V_1_1_1           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL alpha2K_V_1_1                    : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL Constant24_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant25_out1                  : std_logic;
  SIGNAL Subsystem4_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant26_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant23_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant22_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant27_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant28_out1                  : std_logic;
  SIGNAL Subsystem6_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant18_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant17_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant29_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant20_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant21_out1                  : std_logic;
  SIGNAL Subsystem7_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Subsystem7_out1_signed           : signed(31 DOWNTO 0);  -- sfix32_En23
  SIGNAL g_out1                           : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Divide_mul_temp                  : signed(58 DOWNTO 0);  -- sfix59_En46
  SIGNAL Divide_out1                      : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant34_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant31_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant30_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL K_3                              : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL V_3                              : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL alpha2K_not_ascii_V_2V_1_2_2     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL K_not_ascii_V_2V_1_1_2           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL alpha2K_V_1_2                    : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL Constant54_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant55_out1                  : std_logic;
  SIGNAL Subsystem8_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant56_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant53_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant42_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant57_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant58_out1                  : std_logic;
  SIGNAL Subsystem10_out1                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant33_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant32_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant59_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant35_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant36_out1                  : std_logic;
  SIGNAL Subsystem11_out1                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant41_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant38_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant37_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL K_4                              : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL V_4                              : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL alpha2K_not_ascii_V_2V_1_2_3     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL K_not_ascii_V_2V_1_1_3           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL alpha2K_V_1_3                    : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL Constant47_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant48_out1                  : std_logic;
  SIGNAL Subsystem12_out1                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant49_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant46_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant45_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant50_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant51_out1                  : std_logic;
  SIGNAL Subsystem14_out1                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Constant40_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant39_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant52_out1                  : signed(28 DOWNTO 0);  -- sfix29_En23
  SIGNAL Constant43_out1                  : signed(26 DOWNTO 0);  -- sfix27_En23
  SIGNAL Constant44_out1                  : std_logic;
  SIGNAL Subsystem15_out1                 : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Subsystem1 : Subsystem1
    PORT MAP( K => std_logic_vector(K_1),  -- sfix27_En23
              V => std_logic_vector(V_1),  -- sfix27_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1  -- sfix27_En23
              );

  u_Subsystem : Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => DataIn,  -- sfix24_En23
              alpha1_a0 => std_logic_vector(Constant12_out1),  -- sfix27_En23
              a1 => std_logic_vector(Constant1_out1),  -- sfix27_En23
              a2 => std_logic_vector(Constant_out1),  -- sfix27_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1,  -- sfix27_En23
              Cm => std_logic_vector(Constant4_out1),  -- sfix27_En23
              Enable => Constant5_out1,
              DataOut => Subsystem_out1  -- sfix32_En23
              );

  u_Subsystem2 : Subsystem2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => Subsystem_out1,  -- sfix32_En23
              alpha1_a0 => std_logic_vector(Constant6_out1),  -- sfix27_En23
              a1 => std_logic_vector(Constant3_out1),  -- sfix27_En23
              a2 => std_logic_vector(Constant2_out1),  -- sfix27_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1,  -- sfix27_En23
              Cm => std_logic_vector(Constant7_out1),  -- sfix27_En23
              Enable => Constant8_out1,
              DataOut => Subsystem2_out1  -- sfix32_En23
              );

  u_Subsystem3 : Subsystem3
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => Subsystem2_out1,  -- sfix32_En23
              alpha1_a0 => std_logic_vector(Constant11_out1),  -- sfix27_En23
              a1 => std_logic_vector(Constant10_out1),  -- sfix27_En23
              a2 => std_logic_vector(Constant9_out1),  -- sfix27_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1,  -- sfix27_En23
              Cm => std_logic_vector(Constant13_out1),  -- sfix27_En23
              Enable => Constant14_out1,
              DataOut => Subsystem3_out1  -- sfix32_En23
              );

  u_Subsystem5 : Subsystem5
    PORT MAP( K => std_logic_vector(K_2),  -- sfix27_En23
              V => std_logic_vector(V_2),  -- sfix27_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_1,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_1,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_1  -- sfix29_En23
              );

  u_Subsystem4 : Subsystem4
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => Subsystem3_out1,  -- sfix32_En23
              alpha1_a0 => std_logic_vector(Constant19_out1),  -- sfix29_En23
              a1 => std_logic_vector(Constant16_out1),  -- sfix29_En23
              a2 => std_logic_vector(Constant15_out1),  -- sfix29_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_1,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_1,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_1,  -- sfix29_En23
              Cm => std_logic_vector(Constant24_out1),  -- sfix27_En23
              Enable => Constant25_out1,
              DataOut => Subsystem4_out1  -- sfix32_En23
              );

  u_Subsystem6 : Subsystem6
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => Subsystem4_out1,  -- sfix32_En23
              alpha1_a0 => std_logic_vector(Constant26_out1),  -- sfix29_En23
              a1 => std_logic_vector(Constant23_out1),  -- sfix29_En23
              a2 => std_logic_vector(Constant22_out1),  -- sfix29_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_1,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_1,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_1,  -- sfix29_En23
              Cm => std_logic_vector(Constant27_out1),  -- sfix27_En23
              Enable => Constant28_out1,
              DataOut => Subsystem6_out1  -- sfix32_En23
              );

  u_Subsystem7 : Subsystem7
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => Subsystem6_out1,  -- sfix32_En23
              alpha1_a0 => std_logic_vector(Constant18_out1),  -- sfix29_En23
              a1 => std_logic_vector(Constant17_out1),  -- sfix29_En23
              a2 => std_logic_vector(Constant29_out1),  -- sfix29_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_1,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_1,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_1,  -- sfix29_En23
              Cm => std_logic_vector(Constant20_out1),  -- sfix27_En23
              Enable => Constant21_out1,
              DataOut => Subsystem7_out1  -- sfix32_En23
              );

  u_Subsystem9 : Subsystem9
    PORT MAP( K => std_logic_vector(K_3),  -- sfix27_En23
              V => std_logic_vector(V_3),  -- sfix27_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_2,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_2,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_2  -- sfix27_En23
              );

  u_Subsystem8 : Subsystem8
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => std_logic_vector(Divide_out1),  -- sfix27_En23
              alpha1_a0 => std_logic_vector(Constant34_out1),  -- sfix27_En23
              a1 => std_logic_vector(Constant31_out1),  -- sfix27_En23
              a2 => std_logic_vector(Constant30_out1),  -- sfix27_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_2,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_2,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_2,  -- sfix27_En23
              Cm => std_logic_vector(Constant54_out1),  -- sfix27_En23
              Enable => Constant55_out1,
              DataOut => Subsystem8_out1  -- sfix32_En23
              );

  u_Subsystem10 : Subsystem10
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => Subsystem8_out1,  -- sfix32_En23
              alpha1_a0 => std_logic_vector(Constant56_out1),  -- sfix27_En23
              a1 => std_logic_vector(Constant53_out1),  -- sfix27_En23
              a2 => std_logic_vector(Constant42_out1),  -- sfix27_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_2,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_2,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_2,  -- sfix27_En23
              Cm => std_logic_vector(Constant57_out1),  -- sfix27_En23
              Enable => Constant58_out1,
              DataOut => Subsystem10_out1  -- sfix32_En23
              );

  u_Subsystem11 : Subsystem11
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => Subsystem10_out1,  -- sfix32_En23
              alpha1_a0 => std_logic_vector(Constant33_out1),  -- sfix27_En23
              a1 => std_logic_vector(Constant32_out1),  -- sfix27_En23
              a2 => std_logic_vector(Constant59_out1),  -- sfix27_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_2,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_2,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_2,  -- sfix27_En23
              Cm => std_logic_vector(Constant35_out1),  -- sfix27_En23
              Enable => Constant36_out1,
              DataOut => Subsystem11_out1  -- sfix32_En23
              );

  u_Subsystem13 : Subsystem13
    PORT MAP( K => std_logic_vector(K_4),  -- sfix27_En23
              V => std_logic_vector(V_4),  -- sfix27_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_3,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_3,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_3  -- sfix29_En23
              );

  u_Subsystem12 : Subsystem12
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => Subsystem11_out1,  -- sfix32_En23
              alpha1_a0 => std_logic_vector(Constant41_out1),  -- sfix29_En23
              a1 => std_logic_vector(Constant38_out1),  -- sfix29_En23
              a2 => std_logic_vector(Constant37_out1),  -- sfix29_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_3,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_3,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_3,  -- sfix29_En23
              Cm => std_logic_vector(Constant47_out1),  -- sfix27_En23
              Enable => Constant48_out1,
              DataOut => Subsystem12_out1  -- sfix32_En23
              );

  u_Subsystem14 : Subsystem14
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => Subsystem12_out1,  -- sfix32_En23
              alpha1_a0 => std_logic_vector(Constant49_out1),  -- sfix29_En23
              a1 => std_logic_vector(Constant46_out1),  -- sfix29_En23
              a2 => std_logic_vector(Constant45_out1),  -- sfix29_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_3,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_3,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_3,  -- sfix29_En23
              Cm => std_logic_vector(Constant50_out1),  -- sfix27_En23
              Enable => Constant51_out1,
              DataOut => Subsystem14_out1  -- sfix32_En23
              );

  u_Subsystem15 : Subsystem15
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              DataIn => Subsystem14_out1,  -- sfix32_En23
              alpha1_a0 => std_logic_vector(Constant40_out1),  -- sfix29_En23
              a1 => std_logic_vector(Constant39_out1),  -- sfix29_En23
              a2 => std_logic_vector(Constant52_out1),  -- sfix29_En23
              alpha2K_not_ascii_V_2V_1_2 => alpha2K_not_ascii_V_2V_1_2_3,  -- sfix32_En23
              K_not_ascii_V_2V_1_1 => K_not_ascii_V_2V_1_1_3,  -- sfix32_En23
              alpha2K_V_1 => alpha2K_V_1_3,  -- sfix29_En23
              Cm => std_logic_vector(Constant43_out1),  -- sfix27_En23
              Enable => Constant44_out1,
              DataOut => Subsystem15_out1  -- sfix32_En23
              );

  Constant12_out1 <= to_signed(16#07F1F71#, 27);

  Constant1_out1 <= to_signed(-16#0FFF62B#, 27);

  Constant_out1 <= to_signed(16#07F27BB#, 27);

  K_1 <= to_signed(16#001ACF7#, 27);

  V_1 <= to_signed(16#00CE39B#, 27);

  Constant4_out1 <= to_signed(16#02120FB#, 27);

  Constant5_out1 <= '1';

  Constant6_out1 <= to_signed(16#07DA67A#, 27);

  Constant3_out1 <= to_signed(-16#0FFF62B#, 27);

  Constant2_out1 <= to_signed(16#07DA858#, 27);

  Constant7_out1 <= to_signed(16#05A7EFA#, 27);

  Constant8_out1 <= '1';

  Constant11_out1 <= to_signed(16#07CD131#, 27);

  Constant10_out1 <= to_signed(-16#0FFF62B#, 27);

  Constant9_out1 <= to_signed(16#07CC986#, 27);

  Constant13_out1 <= to_signed(16#07BA377#, 27);

  Constant14_out1 <= '1';

  Constant19_out1 <= to_signed(16#000FD873#, 29);

  Constant16_out1 <= to_signed(16#04D40EBF#, 29);

  Constant15_out1 <= to_signed(16#02CA12D7#, 29);

  K_2 <= to_signed(16#1350481#, 27);

  V_2 <= to_signed(16#00F9E5A#, 27);

  Constant24_out1 <= to_signed(16#02120FB#, 27);

  Constant25_out1 <= '1';

  Constant26_out1 <= to_signed(16#000C7F5F#, 29);

  Constant23_out1 <= to_signed(16#04D40EBF#, 29);

  Constant22_out1 <= to_signed(16#01B514E4#, 29);

  Constant27_out1 <= to_signed(16#05A7EFA#, 27);

  Constant28_out1 <= '1';

  Constant18_out1 <= to_signed(16#000B2357#, 29);

  Constant17_out1 <= to_signed(16#04D40EBF#, 29);

  Constant29_out1 <= to_signed(16#01150E56#, 29);

  Constant20_out1 <= to_signed(16#07BA377#, 27);

  Constant21_out1 <= '1';

  Subsystem7_out1_signed <= signed(Subsystem7_out1);

  g_out1 <= to_signed(16#028793E#, 27);

  Divide_mul_temp <= Subsystem7_out1_signed * g_out1;
  Divide_out1 <= Divide_mul_temp(49 DOWNTO 23);

  Constant34_out1 <= to_signed(16#07F1F71#, 27);

  Constant31_out1 <= to_signed(-16#0FFF62B#, 27);

  Constant30_out1 <= to_signed(16#07F27BB#, 27);

  K_3 <= to_signed(16#001ACF7#, 27);

  V_3 <= to_signed(16#018C72A#, 27);

  Constant54_out1 <= to_signed(16#02120FB#, 27);

  Constant55_out1 <= '1';

  Constant56_out1 <= to_signed(16#07DA67A#, 27);

  Constant53_out1 <= to_signed(-16#0FFF62B#, 27);

  Constant42_out1 <= to_signed(16#07DA858#, 27);

  Constant57_out1 <= to_signed(16#05A7EFA#, 27);

  Constant58_out1 <= '1';

  Constant33_out1 <= to_signed(16#07CD131#, 27);

  Constant32_out1 <= to_signed(-16#0FFF62B#, 27);

  Constant59_out1 <= to_signed(16#07CC986#, 27);

  Constant35_out1 <= to_signed(16#07BA377#, 27);

  Constant36_out1 <= '1';

  Constant41_out1 <= to_signed(16#000FD873#, 29);

  Constant38_out1 <= to_signed(16#04D40EBF#, 29);

  Constant37_out1 <= to_signed(16#02CA12D7#, 29);

  K_4 <= to_signed(16#1350481#, 27);

  V_4 <= to_signed(16#01B126F#, 27);

  Constant47_out1 <= to_signed(16#02120FB#, 27);

  Constant48_out1 <= '1';

  Constant49_out1 <= to_signed(16#000C7F5F#, 29);

  Constant46_out1 <= to_signed(16#04D40EBF#, 29);

  Constant45_out1 <= to_signed(16#01B514E4#, 29);

  Constant50_out1 <= to_signed(16#05A7EFA#, 27);

  Constant51_out1 <= '1';

  Constant40_out1 <= to_signed(16#000B2357#, 29);

  Constant39_out1 <= to_signed(16#04D40EBF#, 29);

  Constant52_out1 <= to_signed(16#01150E56#, 29);

  Constant43_out1 <= to_signed(16#07BA377#, 27);

  Constant44_out1 <= '1';

  DataOut <= Subsystem15_out1;

END rtl;

