create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/zynq_ultra_ps_e_0/U0/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/state[0]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[0]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[1]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[2]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[3]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[4]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[5]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[6]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[7]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[8]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[9]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[10]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[11]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[12]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[13]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[14]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[15]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[16]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[17]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[18]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[19]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[20]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[21]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[22]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[23]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[24]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[25]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[26]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[27]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[28]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[29]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[30]} {design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/sample_counter_0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/empty]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/dma_splitter_wrapper_0/U0/dma_splitter_inst/wr_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets ad_mclk_OBUF]
