create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/zynq_ultra_ps_e_0/U0/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_1_muxed[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_3[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 24 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_2[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 24 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_1[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 24 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TData_stage_4[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 24 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_1[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TID_stage_3[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TID_stage_3[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TID_stage_3_prev[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TID_stage_3_prev[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 2 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TID_stage_2[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TID_stage_2[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 2 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TID_stage_1[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/TID_stage_1[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 24 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_2[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 24 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_X_1[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 24 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Prev_Delay_Y_2[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 24 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_2_muxed[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 24 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_Y_1_muxed[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 24 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[0]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[1]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[2]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[3]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[4]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[5]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[6]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[7]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[8]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[9]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[10]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[11]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[12]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[13]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[14]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[15]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[16]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[17]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[18]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[19]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[20]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[21]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[22]} {design_1_i/audio_pipeline_wrapp_0/U0/audio_pipeline_inst/b_filters_and_effects.i_band_low_1/Delay_X_2_muxed[23]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
